# Generated by Django 5.0 on 2023-12-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='цена')),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], max_length=5, verbose_name='валюта')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='цена')),
                ('item', models.ManyToManyField(related_name='orders', to='payments.item')),
            ],
        ),
    ]
